### ISSUE TITLE
Excessive Logging

### ISSUE THREAD

**Issue by sprankhub** [netresearch/deutschepost-module-autocomplete-m2#1]
I see that the extension uses `php-http/logger-plugin` to log outgoing HTTP requests to e.g. autocomplete2.postdirekt.de. It looks like this is done independent of any settings. Any HTTP request seems to be logged, leading to a massively growing `system.log` file. Wouldn't it make sense to only do this when a debug setting is enabled, which should probably be disabled by default?

**Comment by mam08ixo** [comment]
Hi @sprankhub, I can confirm that logging for the `PostDirekt_Autocomplete` module is not configurable.

While we are working on a solution, a temporary fix may be to suppress logging via your project's DI configuration:

```xml
<type name="PostDirekt\Autocomplete\Model\AuthService">
    <arguments>
        <argument name="logger" xsi:type="object">Psr\Log\NullLogger</argument>
    </arguments>
</type>
```
Thank you!

**Comment by sprankhub** [comment]
Thanks for your feedback and the workaround. I have two questions:

1. Are you sure that this only applies to this module and to none of the other modules referenced by `dhl/shipping-m2`?
2. You write that you are working on a solution. Could you give me a rough timeline for this? Is this a matter of days, weeks, months or years? :)

**Comment by mam08ixo** [comment]
Hi @sprankhub, every other module in the metapackage offers a module configuration for logging. They also log to separate files, not `system.log`. If you still find log entries that I am missing, let me know.

Regarding the ETA, a bugfix release _should_ be possible in September.

**Comment by mam08ixo** [comment]
Hi @sprankhub, execute `composer update --with-dependencies dhl/shipping-m2` to install version [1.4.2](https://github.com/netresearch/deutschepost-module-autocomplete-m2/releases/tag/1.4.2) of the `PostDirekt_Autocomplete` module.
